# Generated by Django 6.1 on 2026-08-30 10:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="ชื่อสถานที่")),
                ("description", models.TextField(verbose_name="รายละเอียดสถานที่")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("cafe", "คาเฟ่ / ร้านอาหาร"),
                            ("nature", "ธรรมชาติ / สวนสาธารณะ"),
                            ("temple", "วัด / วัฒนธรรม"),
                            ("market", "ตลาด / ถนนคนเดิน"),
                            ("other", "อื่นๆ"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="หมวดหมู่",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="ที่อยู่ / อำเภอ",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="places/",
                        verbose_name="รูปภาพหน้าปก",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "สถานที่",
                "verbose_name_plural": "สถานที่ทั้งหมด",
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="คะแนน (1-5 ดาว)",
                    ),
                ),
                ("comment", models.TextField(verbose_name="ความคิดเห็นรีวิว")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="reviews/",
                        verbose_name="รูปภาพประกอบรีวิว",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="web.place",
                        verbose_name="สถานที่",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ผู้รีวิว",
                    ),
                ),
            ],
            options={
                "verbose_name": "รีวิว",
                "verbose_name_plural": "รีวิวทั้งหมด",
                "ordering": ["-created_at"],
            },
        ),
    ]
