# Generated by Django 6.1 on 2026-08-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="google_maps_url",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="ลิงก์ Google Maps"
            ),
        ),
        migrations.AddField(
            model_name="place",
            name="latitude",
            field=models.FloatField(blank=True, null=True, verbose_name="ละติจูด"),
        ),
        migrations.AddField(
            model_name="place",
            name="longitude",
            field=models.FloatField(blank=True, null=True, verbose_name="ลองจิจูด"),
        ),
    ]
