# Generated by Django 6.1 on 2026-08-30 12:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_place_google_maps_url_place_latitude_place_longitude"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="comment",
            field=models.TextField(verbose_name="ความคิดเห็น"),
        ),
        migrations.AlterField(
            model_name="review",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="reviews/", verbose_name="รูปภาพประกอบ"
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="คะแนน (1-5)",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="ผู้เขียนรีวิว",
            ),
        ),
        migrations.CreateModel(
            name="ReviewLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="web.review",
                        verbose_name="รีวิว",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ผู้กดถูกใจ",
                    ),
                ),
            ],
            options={
                "verbose_name": "การกดถูกใจรีวิว",
                "verbose_name_plural": "การกดถูกใจรีวิวทั้งหมด",
                "unique_together": {("review", "user")},
            },
        ),
    ]
