# Generated by Django 6.1 on 2026-08-30 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0003_alter_review_comment_alter_review_image_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="ผู้เพิ่มสถานที่",
            ),
        ),
        migrations.AddField(
            model_name="place",
            name="is_approved",
            field=models.BooleanField(default=False, verbose_name="อนุมัติให้แสดงผล"),
        ),
    ]
