# Generated by Django 6.1 on 2026-08-30 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0004_place_created_by_place_is_approved"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("profanity", "มีคำหยาบคายหรือไม่สุภาพ"),
                            ("fake", "ข้อมูลเท็จ / สแปม / โฆษณา"),
                            ("inappropriate_img", "รูปภาพไม่เหมาะสมหรือลามก"),
                            ("other", "อื่นๆ"),
                        ],
                        default="profanity",
                        max_length=30,
                        verbose_name="เหตุผลการรายงาน",
                    ),
                ),
                (
                    "details",
                    models.TextField(
                        blank=True, null=True, verbose_name="รายละเอียดเพิ่มเติม"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="web.review",
                        verbose_name="รีวิวที่ถูกรายงาน",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ผู้รายงาน",
                    ),
                ),
            ],
            options={
                "verbose_name": "การรายงานรีวิว",
                "verbose_name_plural": "การรายงานรีวิวทั้งหมด",
                "unique_together": {("review", "user")},
            },
        ),
    ]
