# Generated by Django 6.1 on 2026-08-30 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0005_reviewreport"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="tags",
            field=models.CharField(
                blank=True,
                help_text="เช่น มีที่จอดรถ, ถ่ายรูปสวย, เปิดดึก, ห้องแอร์",
                max_length=255,
                null=True,
                verbose_name="แท็กไฮไลต์ (คั่นด้วยจุลภาค)",
            ),
        ),
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarked_by",
                        to="web.place",
                        verbose_name="สถานที่โปรด",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ผู้บันทึก",
                    ),
                ),
            ],
            options={
                "verbose_name": "สถานที่โปรด",
                "verbose_name_plural": "สถานที่โปรดทั้งหมด",
                "unique_together": {("user", "place")},
            },
        ),
    ]
