# Generated by Django 6.1 on 2026-09-04 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0008_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="featured_badge",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="เหรียญตราที่เลือกแสดง"
            ),
        ),
    ]
