# Generated by Django 6.1 on 2026-09-03 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0009_tag_review_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="reviews/", verbose_name="รูปภาพประกอบ"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="web.review",
                        verbose_name="รีวิว",
                    ),
                ),
            ],
            options={
                "verbose_name": "รูปภาพรีวิว",
                "verbose_name_plural": "รูปภาพรีวิวทั้งหมด",
            },
        ),
    ]
