# Generated by Django 6.1 on 2026-09-04 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0009_profile_featured_badge"),
        ("web", "0010_reviewimage"),
    ]

    operations = []
