# Generated by Django 6.1 on 2026-09-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0011_merge_0009_profile_featured_badge_0010_reviewimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="category",
            field=models.CharField(
                choices=[
                    ("cafe", "คาเฟ่ / ร้านอาหาร"),
                    ("temple", "วัด / โบราณสถาน"),
                    ("nature", "ธรรมชาติ / สวนสาธารณะ"),
                    ("learning", "พิพิธภัณฑ์ / แหล่งเรียนรู้"),
                    ("market", "ตลาด / ถนนคนเดิน"),
                    ("other", "อื่นๆ"),
                ],
                default="other",
                max_length=20,
                verbose_name="หมวดหมู่",
            ),
        ),
    ]
