# Generated by Django 6.1 on 2026-09-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0012_alter_place_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="contact",
            field=models.CharField(
                blank=True,
                help_text="ตัวอย่าง: 045-612-xxx หรือเพจ Facebook",
                max_length=100,
                null=True,
                verbose_name="ติดต่อ / เบอร์โทร",
            ),
        ),
        migrations.AddField(
            model_name="place",
            name="opening_hours",
            field=models.CharField(
                blank=True,
                help_text="ตัวอย่าง: เปิดทุกวัน 06:00 - 18:00 น. หรือ ปิดทุกวันจันทร์",
                max_length=150,
                null=True,
                verbose_name="เวลาเปิด-ปิดทำการ",
            ),
        ),
    ]
