# Generated by Django 6.1 on 2026-09-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0013_place_contact_place_opening_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="admission_fee",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="ค่าเข้าชม"
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="contact",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="ติดต่อ"
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="opening_hours",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="เวลาทำการ"
            ),
        ),
    ]
